//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public Bus()
        {
            this.ExcursionBusDrivers = new HashSet<ExcursionBusDriver>();
            this.ExcursionTypes = new HashSet<ExcursionType>();
        }
    
        public int busId { get; set; }
        public int capacity { get; set; }
        public bool isOnGoing { get; set; }
        public int mark { get; set; }
        public string numberPlate { get; set; }
        public string color { get; set; }
        public double consumption { get; set; }
    
        public virtual BusMark BusMark { get; set; }
        public virtual ICollection<ExcursionBusDriver> ExcursionBusDrivers { get; set; }
        public virtual ICollection<ExcursionType> ExcursionTypes { get; set; }
    }
}
