//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusMark
    {
        public BusMark()
        {
            this.Buses = new HashSet<Bus>();
        }
    
        public int markId { get; set; }
        public string markName { get; set; }
    
        public virtual ICollection<Bus> Buses { get; set; }
    }
}
