//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int clientId { get; set; }
        public string clientName { get; set; }
        public string clientLastName { get; set; }
        public string phone { get; set; }
        public int country { get; set; }
    
        public virtual ExcursionClient ExcursionClient { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
