//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.ExcursionBusDrivers = new HashSet<ExcursionBusDriver>();
        }
    
        public int driverId { get; set; }
        public bool isOnGoing { get; set; }
        public string number { get; set; }
        public string driverName { get; set; }
        public string driverLastName { get; set; }
        public bool isOnVocation { get; set; }
    
        public virtual ICollection<ExcursionBusDriver> ExcursionBusDrivers { get; set; }
    }
}
