//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excursion
    {
        public Excursion()
        {
            this.ExcursionBusDrivers = new HashSet<ExcursionBusDriver>();
            this.ExcursionClients = new HashSet<ExcursionClient>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int excursionId { get; set; }
        public System.DateTime startDate { get; set; }
        public double duration { get; set; }
        public int distanceKM { get; set; }
        public int countOfCustomers { get; set; }
        public int excursionType { get; set; }
    
        public virtual ExcursionType ExcursionType1 { get; set; }
        public virtual ICollection<ExcursionBusDriver> ExcursionBusDrivers { get; set; }
        public virtual ICollection<ExcursionClient> ExcursionClients { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
