//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcursionClient
    {
        public int excursionClientId { get; set; }
        public int clientId { get; set; }
        public int excursionId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Excursion Excursion { get; set; }
    }
}
